openapi: 3.0.3
info:
  title: Endpoints de Avaliações
  version: "1.0"
  description: |
    API responsável por gerenciar as avaliações comportamentais e de desafios dos colaboradores,
    incluindo cálculo de médias e registro das notas finais.

tags:
  - name: Avaliações
    description: Endpoints para manipulação de avaliações comportamentais e desafios.

paths:
  /avaliacoes/comportamental:
    get:
      tags: [Avaliações]
      summary: Listar avaliações comportamentais por matrícula
      parameters:
        - in: query
          name: matricula
          schema: { type: string }
          required: true
          description: Matrícula do colaborador
        - in: query
          name: data_inicio
          schema: { type: string, format: date }
          required: false
        - in: query
          name: data_fim
          schema: { type: string, format: date }
          required: false
      responses:
        "200":
          description: Lista de avaliações comportamentais
        "400":
          description: Falta o parâmetro matrícula

  /avaliacoes/desafio:
    get:
      tags: [Avaliações]
      summary: Listar avaliações de desafios por matrícula
      parameters:
        - in: query
          name: matricula
          schema: { type: string }
          required: true
          description: Matrícula do colaborador
        - in: query
          name: data_inicio
          schema: { type: string, format: date }
        - in: query
          name: data_fim
          schema: { type: string, format: date }
      responses:
        "200":
          description: Lista de avaliações de desafios

  /avaliacoes/mediaFinalComportamental:
    get:
      tags: [Avaliações]
      summary: Obter médias finais comportamentais por matrícula
      parameters:
        - in: query
          name: matricula
          schema: { type: string }
          required: true
        - in: query
          name: data_inicio
          schema: { type: string, format: date }
        - in: query
          name: data_fim
          schema: { type: string, format: date }
      responses:
        "200":
          description: Lista de médias comportamentais

  /avaliacoes/mediaFinalDesafio:
    get:
      tags: [Avaliações]
      summary: Obter médias finais de desafios por matrícula
      parameters:
        - in: query
          name: matricula
          schema: { type: string }
          required: true
        - in: query
          name: data_inicio
          schema: { type: string, format: date }
        - in: query
          name: data_fim
          schema: { type: string, format: date }
      responses:
        "200":
          description: Lista de médias finais de desafios

  /avaliacoes:
    post:
      tags: [Avaliações]
      summary: Cadastrar nova avaliação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matricula:
                  type: string
                  example: "161000"
                data_avaliacao:
                  type: string
                  format: date
                  example: "2025-10-30"
                comportamental:
                  type: array
                  items:
                    type: object
                    properties:
                      numero_questao: { type: integer, example: 1 }
                      descricao: { type: string, example: "Você promove um ambiente colaborativo?" }
                      nota: { type: integer, example: 4 }
                desafios:
                  type: array
                  items:
                    type: object
                    properties:
                      numero_desafio: { type: integer, example: 1 }
                      descricao: { type: string, example: "Desafio A" }
                      nota: { type: integer, example: 5 }
      responses:
        "201":
          description: Avaliação criada com sucesso
        "400":
          description: Erro de validação ou matrícula inválida

  /avaliacoes/{avaliacao_id}:
    put:
      tags: [Avaliações]
      summary: Atualizar avaliação existente
      parameters:
        - in: path
          name: avaliacao_id
          schema: { type: integer }
          required: true
          description: ID da avaliação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                matricula:
                  type: string
                data_avaliacao:
                  type: string
                comportamental:
                  type: array
                  items:
                    type: object
                    properties:
                      numero_questao: { type: integer }
                      descricao: { type: string }
                      nota: { type: integer }
                desafios:
                  type: array
                  items:
                    type: object
                    properties:
                      numero_desafio: { type: integer }
                      descricao: { type: string }
                      nota: { type: integer }
      responses:
        "200":
          description: Avaliação atualizada com sucesso
        "404":
          description: Avaliação não encontrada

  /avaliacoes/nota_final/{nota_final_id}:
    delete:
      tags: [Avaliações]
      summary: Deletar avaliação por ID de nota final
      parameters:
        - in: path
          name: nota_final_id
          schema: { type: integer }
          required: true
      responses:
        "200":
          description: Avaliação removida com sucesso
        "404":
          description: Nota final não encontrada
