name: Build, Test and Auto PR

on:
  push:
    branches: [ "develop" ]  # dispara quando há push na develop

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

  create-pr:
    name: Create Pull Request to Main
    needs: build-test   # só executa se os testes passarem
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automated PR: Merge tested code from develop → main"
          branch: develop
          base: main
          title: "🚀 Atualização automatizada da develop para main"
          body: |
            Este PR foi criado automaticamente após o build e os testes passarem com sucesso.
            **Aprovação manual é necessária antes do merge.**
          labels: |
            auto-pr
            ready-for-review
